### ISSUE TITLE
Fix bug command

### ISSUE THREAD

**Issue by VortexAcherontic** [Z-Ray-Entertainment/hurby#2]
# About
The !bug command is ... well buggy

![grafik](https://user-images.githubusercontent.com/11244092/192905466-e8daabe9-f358-4da3-ad19-dfce1e50a4af.png)

FIX!

**Comment by VortexAcherontic** [comment]
````
Okt 12 20:44:13 tumblepi hurby.sh[16531]: socket.gaierror: [Errno -2] Name or service not known
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/usr/lib64/python3.10/socket.py", line 955, in getaddrinfo
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/usr/lib64/python3.10/socket.py", line 824, in create_connection
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     return socket.create_connection((host, port), timeout,
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/usr/lib64/python3.10/smtplib.py", line 312, in _get_socket
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     new_socket = super()._get_socket(host, port, timeout)
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/usr/lib64/python3.10/smtplib.py", line 1056, in _get_socket
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     self.sock = self._get_socket(host, port, self.timeout)
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/usr/lib64/python3.10/smtplib.py", line 341, in connect
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     (code, msg) = self.connect(host, port)
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/usr/lib64/python3.10/smtplib.py", line 255, in __init__
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     SMTP.__init__(self, host, port, local_hostname, timeout,
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/usr/lib64/python3.10/smtplib.py", line 1050, in __init__
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     server = smtplib.SMTP_SSL(self.smpt_host, self.smpt_port)
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/tumblepi/data/user/vortex/hurby/applications/hurby/twitch_hurby/cmd/actions/bug_report.py", line 63, in _send_mail
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     self._send_mail(params, character.twitchid)
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/tumblepi/data/user/vortex/hurby/applications/hurby/twitch_hurby/cmd/actions/bug_report.py", line 32, in do_command
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     tmp.do_command(cmd.params, character=char)
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/tumblepi/data/user/vortex/hurby/applications/hurby/twitch_hurby/twitch_receiver.py", line 29, in do_command
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     self.receiver.do_command(cmd, char, self.irc_connector)
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/tumblepi/data/user/vortex/hurby/applications/hurby/twitch_hurby/irc/threads/read_chat.py", line 51, in read_chat
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     self.read_chat()
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/tumblepi/data/user/vortex/hurby/applications/hurby/twitch_hurby/irc/threads/read_chat.py", line 23, in run
Okt 12 20:44:13 tumblepi hurby.sh[16531]:     self.run()
Okt 12 20:44:13 tumblepi hurby.sh[16531]:   File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
Okt 12 20:44:12 tumblepi hurby.sh[16531]: Traceback (most recent call last):
Okt 12 20:44:12 tumblepi hurby.sh[16531]: Exception in thread Thread-3:
````

**Comment by VortexAcherontic** [comment]
Fixed, wrong email credentials
